### ISSUE TITLE
On in-game display...

### ISSUE THREAD

**Issue by adae22** [ParadiseAigo/Tekken-7-Player-Displayer#17]
Hey,

First off, thanks for all the work you've put into this tool!

Now, I've seen your reply to the other question some time back, explaining why you removed the in-game display feature, and I get that.

Nevertheless, I was wondering if there is any chance of that specific feature ever making a return, or is that dead for good?
It really made a world of difference for laptop users, or scenarios where multiple displays aren't an option.

Granted, alt-tabbing isn't the end of the world, but when you play on stick (hands off the keyboard and away from the table), and constantly have to scoot back and forth to switch between the tool and Tekken (since the game seems to love to match you over and over with the same person), the entire dynamic becomes a bit "tedious" after a while.

Again, I genuinely appreciate your efforts on this tool, it has made online Tekken so much better, I just wanted to know if this could be re-implemented or if it's not feasible anymore.

Cheers!

**Comment by ParadiseAigo** [comment]
I was able to fix it! :)

But it's not perfect: in-game you will only be shown their Steam name (not their character or your comment). 

And sometimes Player-Displayer will consistently fail to write their name in-game after you turn off "silent-mode" and give errors instead in the terminal, but restarting Player-Displayer seems to fix that problem.

**Comment by adae22** [comment]
Sorry for getting back to you a little late, was away for a week there.

Just tried out the new version and everything worked flawlessly! Absolutely perfect.

The character is not so much an issue for me personally as long as I know who I'm playing against, so that I can avoid the habitual pluggers and cheaters I run into on a regular basis out here.

Thank you so much for looking into the in-game display, and for taking the time out of your day to fix it, I really appreciate it (as will many others I'm sure, even if they may not make themselves known)!

Cheers, and thanks once more!
