### ISSUE TITLE
CRASHING ON REQUEST

### ISSUE THREAD

**Issue by tskibitzki** [ParadiseAigo/Tekken-7-Player-Displayer#20]
Hey!

For some reason, whenever I get to accept a match the name display outright crashes. no warning, no error it just closes.

Windows 10 w/ admin.

**Comment by ParadiseAigo** [comment]
Okay, I'll take a look at the code again, maybe I can find a fix.

**Comment by ParadiseAigo** [comment]
Here is a different version that hopefully doesn't crash. 
https://github.com/ParadiseAigo/Tekken-7-Player-Displayer/releases/tag/v1.4.0
