### ISSUE TITLE
Program window not remembering last location before closing

### ISSUE THREAD

**Issue by Paulchief** [ParadiseAigo/Tekken-7-Player-Displayer#21]
I have two monitors and I usually use the displayer on the second one.

The problem is that every time I open the program it shows up in the default position on the first monitor rather than on the second monitor where I usually put it.

Can you add a feature where it memorizes the last position it was closed and when you open it up again it opens there?

**Comment by ParadiseAigo** [comment]
Here you go. https://github.com/ParadiseAigo/Tekken-7-Player-Displayer/releases/tag/v1.3.6

To reset the position of the window (make it centered again and put it on the main screen) delete this file:
C:\Users\YourUserName\AppData\Roaming\Player-Displayer-Window-Position.txt

**Comment by Paulchief** [comment]
Thanks bro you are the best
