### ISSUE TITLE
Cant open, black screen

### ISSUE THREAD

**Issue by filete32** [ParadiseAigo/Tekken-7-Player-Displayer#25]
![Screenshot_1](https://user-images.githubusercontent.com/111510481/185395261-af19c4c8-f5d2-46e8-ab4c-a5be10809fd8.png)

**Comment by ParadiseAigo** [comment]
It looks like the gui part of the program is not working for you. I don't know why it's behaving like this on your computer but if everything else (outside of the gui) is still working normally: after opening the program try pressing ALT+T which should open the terminal output of the program. Hopefully you'll still be able to use it that way at least.

**Comment by zoyar94** [comment]
I have the same issue, it suddenly stopped showig GUI in one day, yesterday after about 1 month of no GUI it randomly worked again and today it's black screen again. Kinda weird 😲

**Comment by lMarcMan** [comment]
I started having the same issue about a month ago, I was hoping that if you uploaded a new version for the latest patch it would fix it but nope, the GUI is still off tho the in-game display still works. Messing around I found that older versions work normally, specifically v1.3.3.

**Comment by JRC54** [comment]
Yeah, thats my case too. The app was working just fine but suddenly one day the GUI stopped working and had to download an older version, which were working until new update, now the opponent name doesnt save and doesnt always show and my name is gibberish.

**Comment by BaekIronFist** [comment]
> It looks like the gui part of the program is not working for you. I don't know why it's behaving like this on your computer but if everything else (outside of the gui) is still working normally: after opening the program try pressing ALT+T which should open the terminal output of the program. Hopefully you'll still be able to use it that way at least.

I was able to open it via ALT+T, but could be good to update the current 1.3.8 with this issue fixed, or at least try to find a workaround to display the GUI properly.

**Comment by ParadiseAigo** [comment]
https://github.com/ParadiseAigo/Tekken-7-Player-Displayer/releases/tag/v1.4.0
