### ISSUE TITLE
it works but screen is not appearing

### ISSUE THREAD

**Issue by MohsenEmanAsim** [ParadiseAigo/Tekken-7-Player-Displayer#28]
for some reason, the screen just pops up for like a mili second .i can still use the show name in-game feature, but the screen is not visible.please help.

**Comment by ParadiseAigo** [comment]
I think that deleting the following file and then starting Player-Displayer again after that will fix your problem:
C:\Users\YourUserName\AppData\Roaming\Player-Displayer-Window-Position.txt

But if the above doesn't fix it: while Player-Displayer is running press  alt+t  to open its terminal output which contains all information you get from the gui.

**Comment by MohsenEmanAsim** [comment]
> I think that deleting the following file and then starting Player-Displayer again after that will fix your problem: C:\Users\YourUserName\AppData\Roaming\Player-Displayer-Window-Position.txt
> 
> But if the above doesn't fix it: while Player-Displayer is running press alt+t to open its terminal output which contains all information you get from the gui.

WOAH THANKS :) ALT+ T worked !!!!! back in buisness :) Keep up the good work :)
