### ISSUE TITLE
UI does not open

### ISSUE THREAD

**Issue by anglis007** [ParadiseAigo/Tekken-7-Player-Displayer#31]
When i launch the program it only opens the icon on my task bar , the ui does not open no matter how many times i click on the icon

**Comment by deathrow77** [comment]
Same problem here, this started happening a week ago. I have deleted and re-downloaded the files a few times with no success. If you guys find a solution, please add me on Steam to let me know. Username : 187|Anonymous

**Comment by ParadiseAigo** [comment]
My answer here might be helpful. >_>

https://github.com/ParadiseAigo/Tekken-7-Player-Displayer/issues/28

**Comment by anglis007** [comment]
worked perfectly
