### ISSUE TITLE
Getting steam module base address?

### ISSUE THREAD

**Issue by meikrowaev** [ParadiseAigo/Tekken-7-Player-Displayer#41]
![sma](https://user-images.githubusercontent.com/121307730/209367541-f3d2ae6e-4684-46db-92bf-7476876af474.PNG)

what does this mean and how do i fix it?

**Comment by ParadiseAigo** [comment]
Edit: never mind this comment, look at my next one.
Edit 2: but try it anyway it might tell us something.

Open Tekken 7. Open Task Manager then go to the Details tab. You should find something named "TekkenGame-Win64-Shipping.exe" next to the Tekken icon there. This is the thing that player-displayer needs. Maybe yours has been renamed to something else. Let me know what it says, if it's the same or what.
![Untitled](https://user-images.githubusercontent.com/60544758/209376413-bed49df1-314e-4d87-9dfc-a88b488f40fe.jpg)

**Comment by ParadiseAigo** [comment]
Never mind my previous comment it's not the problem. The problem is that it's not finding this file:
\steamapps\common\TEKKEN 7\Engine\Binaries\ThirdParty\Steamworks\Steamv132\Win64\steam_api64.dll

Has yours been renamed or something?

**Comment by meikrowaev** [comment]
yes i rename it in order to use the dlc unlocker, but even with a clean re install with the appropriate name the issue will still persist, as well as this has never been an issue before with previous updates. i also set everything to run as administrator but no dice

**Comment by meikrowaev** [comment]
ok i figured it out, it was steam being ran as administrator that was messing it up
