### ISSUE TITLE
Ver1.4.5 keep crashing

### ISSUE THREAD

**Issue by Yedsmon** [ParadiseAigo/Tekken-7-Player-Displayer#45]
It's just happened on this week.
At first I was thinking it's a hacking tool to force Player-Displayer to crash (from the opponent players when I am fighting to)
But today the Player-Displayer crash almost every player that I am fight to (some players it crashed more than 1 time in just 1 match)
I started to think that the force crashing may not coming from the players but it may came from BANDAI itself??

Here is the list of players that I fight today (censor name and ID for their privacy)
It crashed almost every player that it so weird...

Dar***			Asuka			(76561198074286***)			warrior 270+ wins (force displayer to closed)
YOU_MOM_IS_M***			Fahkumram			(76561198828389***)			fighter 100+ wins laggg
O***			Bob			(76561199054108***)			not a newbie A+AA (force displayer to closed)
?***			Lucky Chloe			(76561199057539***)			not a newbie (force displayer to closed many times)
ans***			Akuma			(76561198087136***)			initiate A+AA (force displayer to closed many times)
leowye***			Lars			(76561199012543***)			not a newbie (force displayer to closed)
crock***			Jin			(76561199251749***)			seiryu 1k+ wins (force displayer to closed)

**Comment by Yedsmon** [comment]
Update on today morning,
I played for 1 and a half hour without crashing..

Maybe it's a hacking tool from some player that seek for people who use this app and crash them.
I think during I post this message that hacker is still sleeping.

**Comment by ParadiseAigo** [comment]
Thank you for your comments! It should be fixed now in the latest release.

And I don't think that there is a hacker that has nothing better to do than to spend their time annoying player-displayer users by crashing their displayer and also sometimes takes naps in between lol.

But if the hacker does exist, they must have stopped doing it or they were asleep during my last testing session: I annoyingly did not get a single crash in more than 2 hours of testing last weekend using the non-updated version of the displayer. (I was hoping I'd get to test the latest version a bit more.)
