### ISSUE TITLE
Crashing consistently

### ISSUE THREAD

**Issue by TragicFour** [ParadiseAigo/Tekken-7-Player-Displayer#46]
Ver 1.4.5 - silent mode turned off. nothing else used or set (Inc optional feature)

Shows one name correctly then crashes (payer-displayer).
Something is definitely amiss.
So useful too...

**Comment by ParadiseAigo** [comment]
Yes I can confirm it was crashing a lot. It should be fixed now in the latest release. Thank you for the feedback.
