### ISSUE TITLE
Is there plans for a TEKKEN 8 Player Displayer?

### ISSUE THREAD

**Issue by CloudWhisperer** [ParadiseAigo/Tekken-7-Player-Displayer#50]
Hello,
I love the work that you do and it inspires me to learn how to create applications of my own that hook onto currently existing games. I was wondering if you have any plans for tekken 8 as im curious what the code would look like and how it can be implemented into tekken 8, i know its still using unreal engine like tekken 7 but they must have updated the security and tried to hide addresses right?

Thank you,
CloudWhisperer.

**Comment by ParadiseAigo** [comment]
I don't think I will be releasing a version for Tekken 8 anytime soon.

I tried to though, many months ago now, right after T8 came out, but I realized that it wasn't going to be as simple as just reusing the same code. I could be wrong but I don't think there is any special security, it's just that the (Steam) functions they use now for the matchmaking aren't the exact same ones used for T7. And given the new blacklist feature that they added to T8 I figured that my program wasn't that necessary anymore so I kind of gave up. Maybe I'll figure it out in the future.
