### ISSUE TITLE
[Suggestion] Auto decline wifi players

### ISSUE THREAD

**Issue by goudekid** [ParadiseAigo/Tekken-7-Player-Displayer#9]
I mean, while you're poking around in memory anyway, why not emulate keypad right, enter when you detect a wifi connection :p

**Comment by ParadiseAigo** [comment]
You want a "auto-decline wifi player" macro lol. Maybe something more ambitious would be to block the wifi connection in the first place, before it gives you the option to decline; save the poor wifi player from feeling rejected. :)
